#!/bin/bash

# Check if already running

if [ "$cadence_instance_file" ];
then instance_file="$cadence_instance_file";
else instance_file="$HOME/.cadence_instance"
fi

pid_l_num=1
cmd_l_num=2

# 1. Does instance file exists...
if [ -e "$instance_file" ]; then

  # 2. ...PID is valuable and command line matches
  PID=`head -n $pid_l_num "$instance_file" | tail -n 1`;

  # Elements should be checked from left
  if (( PID > 0 )) && [ "`ps -o cmd= $PID`" = "`head -n $cmd_l_num \"$instance_file\" | tail -n 1`" ]; then

    # Tell user about this
    echo "Cadence already started, showing GUI now..."

    # Send SIGUSR2, shows the GUI
    kill -USR2 "$PID"

    # Quit now
    exit
  fi
fi

if [ -f /usr/bin/python3 ]; then
  PYTHON=/usr/bin/python3
else
  PYTHON=python
fi

# We only got here if not running yet
INSTALL_PREFIX="/usr"

# Fill instance file
echo $BASHPID > "$instance_file"
echo $PYTHON $INSTALL_PREFIX/share/cadence/src/cadence.py "$@" >> "$instance_file"

export instance_file
exec $PYTHON $INSTALL_PREFIX/share/cadence/src/cadence.py "$@"
